### ISSUE TITLE
Access tokens aren't 40 characters

### ISSUE THREAD

**Issue by holeyness** [youyanggu/groupme_stats#16]
Hi,
My access token from groupme is not 40 characters. The code works if I just comment out the length check. Mine is 32 characters long.

**Comment by youyanggu** [comment]
It used to be 32 and they made them 40. Maybe they went back to 32? Or maybe you never received an updated one. Not sure...

**Comment by holeyness** [comment]
Yea, you should I guess allow both? Or skip this check and use groupmes error?

**Comment by viveksj** [comment]
Access Token is 32 characters for applications.
If you create an application, then groupme doesn't show you your 40 digit access token, but shows the 32 digit application access token. (I know this, because I created an application by mistake and tried using that token, then figured out the problem, deleted the application and then saw my 40 digit access token)
@youyanggu  Please correct me if I am wrong.

**Comment by youyanggu** [comment]
That makes sense. We now allows both!
